min_version = "2024.9.5"

[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.11"
uv = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[tasks.start]
description = "Start the server"
run = "python server.py"


[settings]
python.uv_venv_auto = true
